name: Build raspios docker image
on:
  workflow_dispatch:
    inputs:
      raspios-release-name:
        description:  Raspios release name
        default: bullseye
      raspios-release-date:
        description:  Raspios release date
        default: 2023-05-03
      latest:
        description: Tag as latest
        type: boolean
        default: false

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install fuse2fs fdisk jq
      - uses: actions/checkout@v3
      - name: Create directory
        run: mkdir out
      - name: Mount image
        env:
          DATE: ${{ github.event.inputs.raspios-release-date }}
          DEBIAN: ${{ github.event.inputs.raspios-release-name }}
        run: ./mount-image.sh out
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: out
          push: true
          platforms: linux/arm64/v8
          build-args: |
            ORG=${{ github.repository_owner }}
            REPO=${{ github.repository }}
          file: Dockerfile
          tags: |-
            ghcr.io/${{ github.repository_owner }}/raspios-lite-${{ github.event.inputs.raspios-release-name }}:${{ github.event.inputs.raspios-release-date }}
            ${{ github.event.inputs.latest && format('ghcr.io/{0}/raspios-lite-{1}:latest', github.repository_owner, github.event.inputs.raspios-release-name) || '' }}
